// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "./cq/providers"
  policy_directory = "./cq/policies"

  connection {
    dsn = """
  }
}


provider "aws" {
  configuration {
  }

  // list of resources to fetch
  resources = [
  ]
}

