name: Clone Releases from Cloudquery/Cloudquery

on:
  schedule:
    # right now we run hourly. I picked 4 after arbitrarily. 4 is a nice number
    - cron: '4 * * * *'
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Releases
        uses: andrewthetechie/gha-clone-releases@v1.2.0
        with:
          token: ${{ secrets.THIS_PAT }}
          repo: cloudquery/cloudquery
          skip_draft: true
          skip_prerelease: true
          # since we're caught up, this will shorten our run times
          min_version: v0.24.0