name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Releases
        with:
          token: ${{ secrets.THIS_PAT }}
          repo: cloudquery/cloudquery