name: Clone Releases from Cloudquery/Cloudquery

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Releases
        uses: andrewthetechie/gha-clone-releases@v1.0.0
        with:
          token: ${{ secrets.THIS_PAT }}
          repo: cloudquery/cloudquery
  